---
- name: Update app list
  sudo: yes
  apt: update_cache=yes

- name: Install packages
  apt: name={{ item }} state=latest
  sudo: yes
  with_items: "packages"

- name: Install extentions
  apt: name={{ item }} state=latest
  sudo: yes
  with_items: "extentions"

- name: Check if composer is installed
  sudo: yes
  stat: path=/bin/composer
  register: composer_exists

- name: Install composer
  sudo: yes
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin creates=/usr/local/bin/composer
  when: not composer_exists.stat.exists

- name: Rename composer.phar to composer
  sudo: yes
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
  when: not composer_exists.stat.exists

- name: Make composer executable
  sudo: yes
  shell: chmod a+x /usr/local/bin/composer
  when: not composer_exists.stat.exists