---
- name: Install packages
  action: apt pkg={{ item }} state=latest
  sudo: yes
  with_items: "packages"

- name: Install extentions
  action: apt pkg={{ item }} state=latest
  sudo: yes
  with_items: "extentions"

- name: Create node symlink
  sudo: yes
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link

- name: Install node modules
  npm: name={{ item }} path=/vagrant/data
  with_items: "node_modules"

- name: Add github.com server to ssh-keyscan
  shell: ssh-keyscan -H -t dsa github.com >> ~/.ssh/known_hosts 2>&1

- name: Add bitbucket.org server to ssh-keyscan
  shell: ssh-keyscan -H -t dsa bitbucket.org >> ~/.ssh/known_hosts 2>&1

- name: Install composer
  sudo: yes
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin creates=/usr/local/bin/composer
  when: not composer_exists.stat.exists

- name: Rename composer.phar to composer
  sudo: yes
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
  when: not composer_exists.stat.exists

- name: Make composer executable
  sudo: yes
  shell: chmod a+x /usr/local/bin/composer
  when: not composer_exists.stat.exists

- name: Update composer
  sudo: yes
  shell: composer self-update
  when: composer_exists.stat.exists

- name: Install codecept
  sudo: yes
  shell: wget http://codeception.com/codecept.phar
  when: not codecept_exists.stat.exists

- name: Rename codecept.phar to codecept
  sudo: yes
  shell: mv codecept.phar /usr/local/bin/codecept
  when: not codecept_exists.stat.exists

- name: Make codecept executable
  sudo: yes
  shell: chmod a+x /usr/local/bin/codecept
  when: not codecept_exists.stat.exists