- name: create webserver groups
  sudo: yes
  group: name=webserver state=present

- name: create webserver accounts
  sudo: yes
  user: name=www-data group=webserver append=yes

- name: create webserver accounts
  sudo: yes
  user: name={{ remote_user }} group=webserver append=yes

- name: Set hostname
  sudo: yes
  hostname: name={{ hostname }}

- name: Add custom domains to /etc/hosts
  sudo: yes
  action: lineinfile state=present dest=/etc/hosts regexp="^127\.0\.0\.1 {{ item }}$" line="127.0.0.1 {{ item }}"
  with_items:
  - web-server
  - "{{ hostname }}"
  - www.{{ hostname }}