---
packages:
  - ufw
  - apache2
  - php5
  - sendmail
  - unzip
  - git
  - vim
  - curl
  - acl
  - mysql-server
  - mysql-client
  - python-mysqldb
  - multitail
  - tree
  - nodejs
  - npm

extentions:
  - php5-mysql
  - php-apc
  - php5-xmlrpc
  - php-soap
  - php5-gd
  - php5-pgsql
  - php5-curl
  - php5-cli
  - php5-xdebug

node_modules:
  - karma
  - karma-mocha
  - chai
  - karma-phantomjs-launcher

apache_modules:
  - rewrite
  - ssl
  - proxy
  - proxy_http
  - proxy_wstunnel
  - headers