---
- hosts: dev-server

  vars_files:
  - vars/dev/config.yml
  - vars/dev/install.yml
  - vars/dev/database.yml
  - vars/dev/firewall.yml
  - vars/dev/symfony.yml
  - vars/shared-hosts.yml
  
  roles:
  - setup
  - dev
